config/routes.rb
Rails.application.routes.draw do
 
  resources :sessions, only: [:new, :create, :destroy]
  resources :users
  root "home#show"
  get '/welcome', to: 'home#show'
  get '/welcome/:first_name', to: 'home#show'
  # get '/gossip', to: 'gossip#show'
  resources :profil
  resources :home
  get '/contact', to: "contact#show"
  get '/team', to: "team#show"
  resources :gossips
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/city.rb
class City < ApplicationRecord
  has_many :users
end

app/models/gossip.rb
class Gossip < ApplicationRecord
  validates :title,
    presence: true,
    length: { minimum: 3, maximum: 14 }

  validates :content,  
    presence: true


  
  
  
  belongs_to :user
  has_many :join_tag_with_gossips
  has_many :tags, through: :join_tag_with_gossips
end

app/models/join_tag_with_gossip.rb
class JoinTagWithGossip < ApplicationRecord
  belongs_to :gossip
  belongs_to :tag
end

app/models/private_message.rb
class PrivateMessage < ApplicationRecord
  belongs_to :sender, class_name: "User"
  belongs_to :recipient, class_name: "User"
end

app/models/tag.rb
class Tag < ApplicationRecord
  has_many :join_tag_with_gossips
  has_many :gossips, through: :join_tag_with_gossips
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password
  
  belongs_to :city, optional: true
  has_many :gossips
  has_many :sent_messages, foreign_key: 'sender_id', class_name: "PrivateMessage"
  has_many :received_messages, foreign_key: 'recipient_id', class_name: "PrivateMessage"
  
end

app/controllers/contact_controller.rb
class ContactController < ApplicationController
  def show
  end
end

app/controllers/gossip_controller.rb
class GossipController < ApplicationController
  def show
    puts "$" * 60
    puts "Voici le message de l'URL :"
    puts  params[:id]
    puts "$" * 60
    @id = params[:id]
    @gossip = Gossip.find(params[:id])
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  
  

  
  def show
    puts "$" * 60
    puts "Voici le message de l'URL :"
    puts  params[:first_name]
    puts "$" * 60
    @first_name = params[:first_name]
    @gossips = Gossip.all
  end
end

app/controllers/profil_controller.rb
class ProfilController < ApplicationController
  def show
    puts "$" * 60
    puts "Voici le message de l'URL :"
    puts  params[:id]
    puts "$" * 60
    @id = params[:id]
  end
end

app/controllers/team_controller.rb
class TeamController < ApplicationController
  def show
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    def new
        @user = User.new
    end
    
    def create
        @user = User.new(user_params)
        if @user.save
          session[:user_id] = @user.id # Login l'utilisateur après l'inscription
          redirect_to root_path, notice: 'Inscription réussie !'
        else
             # Ajoutez cette ligne pour afficher les erreurs
    
          render :new
        end
    end

    private

    def user_params
        params.require(:user).permit(:first_name, :last_name, :description, :email, :age, :city_id, :password, :password_confirmation)
    end



end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/contact_helper.rb
module ContactHelper
end

app/helpers/gossip_helper.rb
module GossipHelper
end

app/helpers/gossips_helper.rb
module GossipsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/profil_helper.rb
module ProfilHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
    
    def current_user
        User.find_by(id: session[:user_id])
    end
    
    def log_in(user)
        session[:user_id] = user.id
    end
    
   

end

app/helpers/team_helper.rb
module TeamHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/contact/show.html.erb
<h1>Contact#show</h1>
<p>Find me in app/views/contact/show.html.erb</p>
<p>Tu veux nous contacter ?</p>

app/views/home/index.html.erb
<h1>Bienvenue <%= @user.first_name %> <%= @user.last_name %> sur votre tableau de bord !</h1>

app/views/home/show.html.erb
<main role="main">

      <!-- Main jumbotron for a primary marketing message or call to action -->



<div class="jumbotron">
        <div class="container">
          <h1 class="display-3">Bienvenue sur le site de potins !</h1>
          <p>Bienvenue sur "The Gossip Project" ! Ici, chaque moussaillon a le pouvoir de partager, éditer et même effacer ses gossips. Libérez votre esprit bavard et laissez les commentaires s'épanouir. Préparez-vous à plonger dans l'univers palpitant des potins à The Hacking Project !</p>
        </div>

        <div class="grid text-center px-5 py-3">
          <%= link_to "Crée ton Potin !", new_gossip_path, class: "btn btn-primary btn-lg btn-block" %>
        </div>
</div>

<div class="container">
  <div class="row">
    <% @gossips.each do |gossip| %>
      <div class="col-md-4">
        <div class="card mb-4 box-shadow">
          <div class="card-body">
            <h2 class="card-title"><%= gossip.title %></h2>
            <p class="card-text">Auteur : <%= gossip.user.first_name %></p>
            <div class="d-flex justify-content-between align-items-center">
              <%= link_to "Lire Le Potin", gossip_path(gossip), class: "btn btn-primary btn-sm" %>
              <%= link_to "Description Auteur", profil_path(gossip), class: "btn btn-secondary btn-sm" %>
              <%= link_to "Modifer Potin", edit_gossip_path(gossip), class: "btn btn-secondary btn-sm" %>
            </div>
          </div>
        </div>
      </div>
    <% end %>
  </div>
</div>






</main>










    <% if notice.present? %>
      <div class="alert alert-success">
      <%= notice %>
      </div>
    <% end %>

app/views/profil/show.html.erb
<div class="my-5">
  <div class="p-5 text-center bg-body-tertiary">
    <div class="container py-5">
      <h1 class="text-body-emphasis">Profil</h1>
      <p class="col-lg-8 mx-auto lead">
        First_name : <%= Gossip.find(@id).user.first_name %><br/>
        Last_name : <%= Gossip.find(@id).user.last_name %><br/>
        Description : <%= Gossip.find(@id).user.description %><br/>
        Email : <%= Gossip.find(@id).user.email %><br/>
        Age : <%= Gossip.find(@id).user.age %><br/>
        City : <%= Gossip.find(@id).user.city.name %><br/>
      </p>
    </div>
  </div>
</div>

app/views/team/show.html.erb
<h1>Team#show</h1>
<p>Find me in app/views/team/show.html.erb</p>
<p>"voici notre équipe lol mdr 😇❤️😻"</p>