config/routes.rb
Rails.application.routes.draw do
 
  resources :sessions, only: [:new, :create, :destroy]
  resources :users
  root "home#show"
  get '/welcome', to: 'home#show'
  get '/welcome/:first_name', to: 'home#show'
  # get '/gossip', to: 'gossip#show'
  resources :profil
  resources :home
  get '/contact', to: "contact#show"
  get '/team', to: "team#show"
  resources :gossips
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/city.rb
class City < ApplicationRecord
  has_many :users
end

app/models/gossip.rb
class Gossip < ApplicationRecord
  validates :title,
    presence: true,
    length: { minimum: 3, maximum: 14 }

  validates :content,  
    presence: true


  
  
  
  belongs_to :user
  has_many :join_tag_with_gossips
  has_many :tags, through: :join_tag_with_gossips
end

app/models/join_tag_with_gossip.rb
class JoinTagWithGossip < ApplicationRecord
  belongs_to :gossip
  belongs_to :tag
end

app/models/private_message.rb
class PrivateMessage < ApplicationRecord
  belongs_to :sender, class_name: "User"
  belongs_to :recipient, class_name: "User"
end

app/models/tag.rb
class Tag < ApplicationRecord
  has_many :join_tag_with_gossips
  has_many :gossips, through: :join_tag_with_gossips
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password
  
  belongs_to :city, optional: true
  has_many :gossips
  has_many :sent_messages, foreign_key: 'sender_id', class_name: "PrivateMessage"
  has_many :received_messages, foreign_key: 'recipient_id', class_name: "PrivateMessage"
  
end

app/controllers/gossip_controller.rb
class GossipController < ApplicationController
  def show
    puts "$" * 60
    puts "Voici le message de l'URL :"
    puts  params[:id]
    puts "$" * 60
    @id = params[:id]
    @gossip = Gossip.find(params[:id])
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  
  

  
  def show
    puts "$" * 60
    puts "Voici le message de l'URL :"
    puts  params[:first_name]
    puts "$" * 60
    @first_name = params[:first_name]
    @gossips = Gossip.all
  end
end

app/controllers/team_controller.rb
class TeamController < ApplicationController
  def show
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    def new
        @user = User.new
    end
    
    def create
        @user = User.new(user_params)
        if @user.save
          session[:user_id] = @user.id # Login l'utilisateur après l'inscription
          redirect_to root_path, notice: 'Inscription réussie !'
        else
             # Ajoutez cette ligne pour afficher les erreurs
    
          render :new
        end
    end

    private

    def user_params
        params.require(:user).permit(:first_name, :last_name, :description, :email, :age, :city_id, :password, :password_confirmation)
    end



end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/contact_helper.rb
module ContactHelper
end

app/helpers/gossip_helper.rb
module GossipHelper
end

app/helpers/gossips_helper.rb
module GossipsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/profil_helper.rb
module ProfilHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
    
    def current_user
        User.find_by(id: session[:user_id])
    end
    
    def log_in(user)
        session[:user_id] = user.id
    end
    
   

end

app/helpers/team_helper.rb
module TeamHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TheGossipProject</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    

    <%# ajout de bootstrap %>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.8/dist/umd/popper.min.js" integrity="sha384-I7E8VVD/ismYTF4hNIPjVp/Zjvgyol6VFvRkX/vR+Vc4jQkC+hVqc2pM8ODewa9r" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.min.js" integrity="sha384-BBtl+eGJRgqQAUMxJ7pMwbEyER4l1g+O15P+16Ep7Q9Q+zqX6gSbd85u4mG4QzX+" crossorigin="anonymous"></script>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL" crossorigin="anonymous"></script>

    <%= csrf_meta_tags %>

  </head>

  <body data-turbo="false">

  <% flash.each do |key, message| %>
    <div class="alert alert-<%= key %>">
      <%= message %>
    </div>
  <% end %>

    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
      <a class="navbar-brand h1" href="/welcome">The gossip project</a>
      <%# link_to "The gossip project", welcome_path, class: "navbar-brand" %>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNav">
        <ul class="navbar-nav">
          <li class="nav-item">
            <%= link_to "Contact", contact_path, class: "nav-link" %>
            <%#<a class="nav-link" href="/contact">Contact</a> %>
          </li>
          <li class="nav-item">
            <%= link_to "Team", team_path, class: "nav-link" %>
            <%# <a class="nav-link" href="/team">Team</a> %>
          </li>
          <li class="nav-item">
            <%= link_to "S'inscrire", new_user_path, class: "nav-link" %>
            <%# <a class="nav-link" href="/users">Users</a> %>
          </li>
          <li class="nav-item">
            <%= link_to "Connexion", new_session_path, class: "nav-link" %>
            <%# <a class="nav-link" href="/sessions">Sessions</a> %>
          </li>
          <li class="nav-item">
          <%= link_to "Se déconnecter", session_path(session.id), method: :delete %>
          </li>
        </ul>
      </div>
    </nav>
    <%= yield %>
  </body>
</html>